### ISSUE TITLE
Tutorial: tracing code

### ISSUE THREAD

**Issue by jayasting98** [AY2122S1-CS2103T-W17-3/tp#1]
Around the start of the tutorial
![IDE around the start of the tutorial](https://user-images.githubusercontent.com/65202977/133396124-2a70d66d-9e6c-46a0-9851-22fc71dde32d.png)
Around the end of EditCommandParser::parse
![IDE debug sub-window around the end of EditCommandParser::parse](https://user-images.githubusercontent.com/65202977/133396139-8febcf04-6d3d-493f-8538-beeebd79b543.png)
Around the end of EditCommand::execute
![IDE around the end of EditCommand::execute](https://user-images.githubusercontent.com/65202977/133396159-0c19a954-d68e-4239-8877-c757dbc62a45.png)

**Comment by wonyeji** [comment]
<img width="1440" alt="Screenshot 2021-09-26 at 7 36 29 PM" src="https://user-images.githubusercontent.com/75670073/134805996-e9ce9917-c6b4-4841-bb76-a827971dbac7.png">
