### ISSUE TITLE
[PE-D] Suggested Improvement: Specify person added in command response.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-3/tp#248]
Am unable to tell from the command response who I have added into a group.
It will be good to include details of person that has been added to group in the command result for easy confirmation that user has executed correct command.

![image.png](https://raw.githubusercontent.com/Justinhoejj/ped/main/files/d339ca5c-a2e1-4c08-b3d5-2b0099d4e1c7.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Justinhoejj/ped#9

**Comment by wonyeji** [comment]
We will not take this suggestion.
