### ISSUE TITLE
[PE-D] joinG Command works when not provided a person

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-3/tp#251]
The command `joinG g/1` will go through, with a message like "Person(s) added to group : CS1231S". Since it doesn't make much sense for a command to add no one to a group, I would like to suggest making this an invalid command.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kaldius/ped#4

**Comment by wonyeji** [comment]
duplicate
