### ISSUE TITLE
[PE-D] Making a person join a group they are already in

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-3/tp#254]
The command just straight up is not accepted by the application. There's no warning whatsoever

![Screenshot 2021-10-29 at 4.51.29 PM.png](https://raw.githubusercontent.com/DonnyS57/ped/main/files/d3aa0dd5-2719-4129-a346-a495f83e043a.png)

^^ nothing happens if you press enter

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: DonnyS57/ped#5

**Comment by wonyeji** [comment]
duplicate
