### ISSUE TITLE
[PE-D] Adding duplicate persons to a group does not show an appropriate error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-3/tp#259]
Steps to reproduce: 

1. Begin from a state where there are no members in any of the groups.

![image.png](https://raw.githubusercontent.com/rgbpokka/ped/main/files/51b7f8b3-80af-4df1-9cc8-8a3f2b8a5756.png)

2. Key in `joinG p/1 p/2 g/3`

3. Key in `joinG p/1 p/2 p/3 g/3`

Expected: Some kind of error message stating that the person that the user is trying to add into the group is a duplicate person. 

Actual: The previous command message is displayed instead. 

![image.png](https://raw.githubusercontent.com/rgbpokka/ped/main/files/c5670138-246e-47d6-94c6-c4e2a98ca073.png)

However, the person identified by index 3 (the person that is not yet in the group 3) does get added to the group, hence I would consider the severity of this bug to be low. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: rgbpokka/ped#6

**Comment by wonyeji** [comment]
duplicate

**Comment by jayasting98** [comment]
See #264
