### ISSUE TITLE
[PE-D] Minor Inconsistency for addT command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-3/tp#260]
According to UG, the added task is marked as `undone`.

![image.png](https://raw.githubusercontent.com/rgbpokka/ped/main/files/f74ad186-d403-4f60-8f34-206ac06107d3.png)

However, on the UI, it shows `Not done`. 

![image.png](https://raw.githubusercontent.com/rgbpokka/ped/main/files/847c8f4e-8aa4-4065-92a8-a833f26c0a05.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: rgbpokka/ped#7

**Comment by wonyeji** [comment]
change to not done

**Comment by thanwinnikki** [comment]
Resolved.
