### ISSUE TITLE
[PE-D] Unable to delete person from Group Information Panel

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-3/tp#266]
UG suggest that this should be allowed but did not manage to delete person successfully from group information panel.

Steps to reproduce:

* create group

* create person

* add person to group

* checkout group information to view groupmates and task

* execute delete command

![image.png](https://raw.githubusercontent.com/Justinhoejj/ped/main/files/4a9ff261-2aab-41d7-b048-c7ad381eadad.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Justinhoejj/ped#17

**Comment by wonyeji** [comment]
remove the page from ug

**Comment by thanwinnikki** [comment]
Resolved.
