### ISSUE TITLE
[PE-D] Typo in user guide - edit command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-3/tp#275]
Panel should be plural.

![image.png](https://raw.githubusercontent.com/Justinhoejj/ped/main/files/9b7dbaf3-bcb9-44e1-9bf0-fe00e564d257.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Justinhoejj/ped#26

**Comment by thanwinnikki** [comment]
Resolved.
