### ISSUE TITLE
[PE-D] Typo in userguide - delete command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-3/tp#278]
Panel should be plural.

![image.png](https://raw.githubusercontent.com/Justinhoejj/ped/main/files/f8f491aa-f174-4af9-80da-259f43de2be6.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Justinhoejj/ped#29

**Comment by thanwinnikki** [comment]
Resolved.
