### ISSUE TITLE
[PE-D] For some reason this command doesn't work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-3/tp#280]
![image.png](https://raw.githubusercontent.com/kaldius/ped/main/files/56abadc4-a026-4acd-aa08-58dc65f1b4e3.png)

I actually can't find out why but I just thought it would be good for yall to know.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kaldius/ped#8

**Comment by asherhy** [comment]
This is because address is null in number 7
