### ISSUE TITLE
Update title and introduction of the Project Portfolio Page

### ISSUE THREAD

**Issue by hungkhoaitay** [AY2122S1-CS2103T-W17-3/tp#29]
Can someone help update title and introduction of the Project Portfolio Page 😄

**Comment by thanwinnikki** [comment]
I think we have to add that ourselves. See my pull request #35 under files changed as a reference.

**Comment by jayasting98** [comment]
I think so too. I think we each wrote something so this should be complete. We may need to standardise it across our pages later though, but that's probably a separate issue. I will close this for now.
